kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: arctiq-backend-production
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: arctiq
        role: backend
        env: production
    spec:
      containers:
      - name: backend
        image: gcr.io/cloud-solutions-images/arctiq:1.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        command: ["sh", "-c", "app -port=8080"]
        ports:
        - name: backend
          containerPort: 8080
