kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: arctiq-frontend-production
spec:
  replicas:
  template:
    metadata:
      name: frontend
      labels:
        app: arctiq
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: gcr.io/cloud-solutions-images/arctiq:1.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        command: ["sh", "-c", "app -frontend=true -backend-service=http://arctiq-backend:8080 -port=80"]
        ports:
        - name: frontend
          containerPort: 80
