kind: Service
apiVersion: v1
metadata:
  name: arctiq-frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: arctiq
    role: frontend
